# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-07 07:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yunwei',
            name='title',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='web.listt'),
            preserve_default=False,
        ),
    ]
